<?php $titulo='Diseñá tu mesada'; include 'includes/header.php'; ?>
<section class="config-intro"><p class="eyebrow">Diseñá tu mesada y pedí presupuesto</p><h1>De una idea aproximada a una consulta concreta.</h1><p>Las medidas son orientativas. Antes de fabricar realizamos una medición profesional.</p></section>
<form class="configurator" id="budgetForm" action="guardar-proyecto.php" method="post" enctype="multipart/form-data">
  <div class="config-nav" aria-label="Progreso"><span class="on">01 Tipo</span><span>02 Forma</span><span>03 Aspecto</span><span>04 Datos</span></div>
  <div class="config-grid">
    <div class="config-controls">
      <fieldset><legend>¿Qué querés hacer?</legend><div class="choice-row"><?php foreach(['Cocina','Baño','Quincho','Mesa','Otro'] as $v): ?><label><input type="radio" name="tipo" value="<?= $v ?>" <?= $v==='Cocina'?'checked':'' ?>><span><?= $v ?></span></label><?php endforeach; ?></div></fieldset>
      <fieldset><legend>Elegí una forma</legend><div class="shape-row"><?php foreach(['Recta','En L','En U','Con isla','Personalizada'] as $v): ?><label><input type="radio" name="forma" value="<?= $v ?>" <?= $v==='En L'?'checked':'' ?>><span><?= $v ?></span></label><?php endforeach; ?></div></fieldset>
      <fieldset><legend>Medidas aproximadas</legend><div class="fields"><label>Largo A <input name="lado_a" type="number" min="20" max="1000" value="240"> <small>cm</small></label><label>Largo B <input name="lado_b" type="number" min="20" max="1000" value="160"> <small>cm</small></label><label>Profundidad <input name="profundidad" type="number" min="20" max="150" value="60"> <small>cm</small></label></div></fieldset>
      <fieldset><legend>Configurá el aspecto</legend><div class="fields"><label>Material<select name="material"><?php foreach($materiales as $m): ?><option><?= $m['nombre'] ?></option><?php endforeach; ?></select></label><label>Muebles<select name="muebles"><option>Blanco</option><option>Madera clara</option><option>Madera oscura</option><option>Grafito</option></select></label><label>Bacha<select name="bacha"><option>Bajo mesada</option><option>Sobrepuesta</option><option>Sin bacha</option></select></label><label>Espesor visible<select name="espesor"><option>2 cm</option><option selected>4 cm</option><option>6 cm</option><option>Ingletado especial</option></select></label><label>Frente / zócalo<select name="frente"><option>Sin frente</option><option>5 cm</option><option selected>7 cm</option><option>10 cm</option></select></label><label>Anafe<select name="anafe"><option>Sin anafe</option><option>Eléctrico</option><option>A gas</option></select></label></div></fieldset>
      <fieldset><legend>Fotos y aclaraciones</legend><label class="upload">Foto o plano (JPG, PNG o PDF, hasta 6 MB)<input type="file" name="archivo" accept="image/jpeg,image/png,image/webp,application/pdf"></label><label>Observaciones<textarea name="observaciones" rows="3" placeholder="Contanos algo importante sobre el espacio"></textarea></label></fieldset>
      <fieldset><legend>Datos de contacto</legend><div class="fields"><label>Nombre<input name="nombre" required autocomplete="name"></label><label>Teléfono<input name="telefono" required inputmode="tel" autocomplete="tel"></label><label>Barrio o zona<input name="zona"></label><label>¿Cuándo te gustaría hacerlo?<select name="plazo"><option>Estoy averiguando</option><option>Dentro de 1 mes</option><option>Entre 1 y 3 meses</option><option>Más adelante</option></select></label></div></fieldset>
      <button class="button submit" type="submit">Guardar y consultar por WhatsApp</button>
    </div>
    <aside class="live-preview"><div class="kitchen"><div class="wall"></div><div class="counter shape-l"><span class="sink"></span><span class="cooktop"></span></div><div class="cabinets"><i></i><i></i><i></i></div><div class="measure a">240 cm</div><div class="measure b">160 cm</div></div><div class="preview-data"><span>Vista aproximada</span><dl><div><dt>Proyecto</dt><dd data-out="tipo">Cocina</dd></div><div><dt>Forma</dt><dd data-out="forma">En L</dd></div><div><dt>Material</dt><dd data-out="material">Rosa Portugal</dd></div><div><dt>Muebles</dt><dd data-out="muebles">Blanco</dd></div><div><dt>Bacha</dt><dd data-out="bacha">Bajo mesada</dd></div><div><dt>Espesor</dt><dd data-out="espesor">4 cm</dd></div></dl></div></aside>
  </div>
</form>
<?php include 'includes/footer.php'; ?>
