<!doctype html>
<html lang="es-AR">
<head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Materiales · Marmolería Marceillac</title><link rel="icon" href="assets/img/logo.jpg">
  <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600&family=Newsreader:opsz,wght@6..72,400;6..72,500&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="assets/css/redesign.css?v=3">
  
<script defer src="assets/js/materiales/menu.js?v=9"></script><script defer src="assets/js/materiales/catalogo.js?v=9"></script><script defer src="assets/js/materiales/explorador.js?v=9"></script><link rel="stylesheet" href="assets/css/studio.css?v=9"></head>
<body>
  <div class="utility"><span>Olazábal 1045 · Mar del Plata</span><span>Lun–Vie 8–16 h · Sáb 9–12 h</span><a href="tel:2234739138">223 473-9138</a></div>
  <header class="site-head"><a class="logo" href="index.php"><img src="assets/img/logo.jpg" alt="Marmolería Marceillac"><span><strong>MARCEILLAC</strong><small>MARMOLERÍA · DESDE 1915</small></span></a><button class="menu">Menú</button><nav class="nav"><a href="index.php">Inicio</a><a href="configurador.php">Diseñá tu mesada</a><a class="active" href="materiales.php">Materiales</a><a href="nosotros.php">Nosotros</a><a href="contacto.php">Contacto</a></nav><div class="socials"><a href="https://wa.me/5492236191251" aria-label="WhatsApp"><svg viewBox="0 0 24 24"><path d="M20 11.7a8 8 0 0 1-11.8 7L4 20l1.4-4A8 8 0 1 1 20 11.7Z"/><path d="M9 8.5c.6 2.2 2 3.6 4.3 4.5l1.2-1.2 2 .9c-.2 1.3-1 2.2-2.3 2.3-3.7-.3-6.8-3.3-7.2-7 .1-1.2.8-2 2-2.3l1 1.8Z"/></svg></a><a href="https://www.instagram.com/marmoleriamarceillac/" aria-label="Instagram"><svg viewBox="0 0 24 24"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><path d="M17.5 6.5h.01"/></svg></a><a href="mailto:marmoleriamarceillac@gmail.com" aria-label="Email"><svg viewBox="0 0 24 24"><rect x="3" y="5" width="18" height="14" rx="1"/><path d="m4 7 8 6 8-6"/></svg></a></div></header>
  <main>
    <section class="page-hero"><p class="kicker">Colección de materiales</p><h1>Cada piedra tiene<br>su carácter.</h1><p>Explorá 12 texturas de alta definición en el estudio y las 69 muestras del catálogo. Elegí una superficie y probala en una cocina 3D.</p><div class="actions"><a class="btn" href="configurador.php">Diseñá tu mesada</a></div></section>
    <section class="material-layout" data-materials>
      <div class="material-stage" style="background-image:url('assets/img/pbr/Marble019/Marble019_2K-JPG_Color.jpg')"><div class="material-title"><p class="kicker" data-material-family>Mármol</p><h2 data-material-name>Blanco de veta gris</h2><small data-material-note>Textura ilustrativa · no representa una placa en stock</small><a class="btn light" data-try-material href="configurador.php?material=1001">Ver en mi cocina ↗</a></div></div>
      <aside class="material-panel"><p class="kicker">Explorá las muestras</p><p>Estudio: texturas libres ilustrativas. Catálogo: fotografías de referencia de los materiales del taller.</p><div class="collection-switch" role="group" aria-label="Colección"><button type="button" data-collection="Estudio" aria-pressed="true">Estudio · 12</button><button type="button" data-collection="Catálogo" aria-pressed="false">Catálogo · 69</button></div><div data-samples></div></aside>
    </section>
    <section class="section material-guide"><div class="section-head"><div><p class="kicker">Guía rápida</p><h2>Tres familias,<br>distintos usos.</h2></div><p>La elección depende del ambiente, del mantenimiento que querés dedicarle y de cuánto contacto tendrá con calor, líquidos y alimentos.</p></div>
      <div class="guide-grid">
        <article class="guide-card"><span class="guide-number">01 / Piedra natural</span><h3>Mármol</h3><p>Vetas que no se repiten. Es una elección expresiva para baños, mesas y revestimientos; también puede usarse en cocina si aceptás una superficie más delicada y cuidás los ácidos, las manchas y los golpes.</p><b>Elegilo por su veta y carácter.</b></article>
        <article class="guide-card"><span class="guide-number">02 / Piedra natural</span><h3>Granito</h3><p>Resistente al uso diario y al calor habitual de una cocina. Su dibujo puede ir de granos discretos a vetas muy marcadas. Funciona especialmente bien en mesadas de cocina y quinchos.</p><b>Elegilo para un uso intenso.</b></article>
        <article class="guide-card"><span class="guide-number">03 / Superficie elaborada</span><h3>Cuarzo</h3><p>Ofrece colores consistentes, acabados uniformes y buena resistencia a manchas comunes. Va muy bien en interiores; el calor directo de ollas o parrillas exige protección. Silestone es una marca, no el nombre de todos los cuarzos.</p><b>Elegilo por su uniformidad.</b></article>
      </div>
      <div class="comparison"><div class="comparison-heading"><p class="kicker">Comparador práctico</p><h3>Una decisión más clara.</h3><p>Valores orientativos: el acabado, la porosidad y el cuidado real de cada placa pueden cambiar el resultado. Siempre conviene confirmar el uso con el taller.</p></div><div class="comparison-scroll"><table><thead><tr><th scope="col">Material</th><th scope="col">Calor</th><th scope="col">Manchas</th><th scope="col">Mantenimiento</th><th scope="col">Usos habituales</th></tr></thead><tbody><tr><th scope="row">Granito</th><td>Alta resistencia</td><td>Buena con sellado adecuado</td><td>Bajo a moderado</td><td>Cocinas y quinchos</td></tr><tr><th scope="row">Mármol</th><td>Resiste el calor, pero se marca</td><td>Sensible a ácidos y líquidos</td><td>Más atento</td><td>Baños, mesas y piezas especiales</td></tr><tr><th scope="row">Cuarzo</th><td>Evitar calor directo</td><td>Buena en uso normal</td><td>Bajo</td><td>Interiores y cocinas</td></tr></tbody></table></div></div>
      <div class="material-advice"><div><p class="kicker">Cómo elegimos juntos</p><h3>No se decide sólo por una foto.</h3></div><p>Contanos dónde irá la mesada y cómo la usás. Podemos revisar el color de la placa real, el sentido de la veta, los cantos, la bacha y el espesor antes del corte.</p><a class="btn" href="contacto.php">Consultar material</a></div>
    </section>
    <section class="cta rust"><h2>De la muestra a la pieza.</h2><a class="btn light" href="configurador.php">Diseñá tu mesada</a></section>
  </main>
  <footer class="site-footer"><div><p class="kicker">Marmolería Marceillac</p><h3>Piedras para arquitectura y diseño.</h3></div><nav><a href="index.php">Inicio</a><a href="configurador.php">Diseñá tu mesada</a><a href="nosotros.php">Nosotros</a><a href="contacto.php">Contacto</a></nav><div><p>Olazábal 1045 · Mar del Plata<br>223 473-9138</p></div></footer>
</body></html>
