<?php $titulo='Materiales'; include 'includes/header.php'; ?>
<section class="page-hero"><p class="eyebrow">Explorador de materiales</p><h1>La veta define el carácter.</h1><p>Acercate a cada superficie, cambiá la luz y guardá tus favoritas para consultarlas.</p></section>
<section class="material-explorer" data-material-explorer>
  <div class="material-stage" style="--material:url('<?= $materiales[0]['imagen'] ?>')"><div class="light-filter"></div><div class="stage-label"><span id="materialType"><?= $materiales[0]['tipo'] ?></span><h2 id="materialName"><?= $materiales[0]['nombre'] ?></h2></div><button id="favoriteMaterial" class="favorite" aria-pressed="false">☆ Guardar muestra</button></div>
  <aside><label>Luz<select id="lightMode"><option value="natural">Natural</option><option value="warm">Cálida</option><option value="cold">Fría</option></select></label><p class="hint">Mové el cursor sobre la placa para recorrer la veta.</p><div class="sample-list">
  <?php foreach ($materiales as $i=>$m): ?><button class="sample <?= $i===0?'selected':'' ?>" data-name="<?= htmlspecialchars($m['nombre']) ?>" data-type="<?= $m['tipo'] ?>" data-image="<?= htmlspecialchars($m['imagen']) ?>"><i style="--swatch:<?= $m['tono'] ?>"></i><span><?= $m['nombre'] ?><small><?= $m['tipo'] ?></small></span></button><?php endforeach; ?>
  </div></aside>
</section>
<section class="comparison"><div class="section-head"><p class="eyebrow">Elegir con criterio</p><h2>Comparación práctica.</h2><select id="useCase"><option value="all">Uso general</option><option value="kitchen">Cocina familiar</option><option value="quincho">Quincho</option><option value="bath">Baño</option></select></div><div class="table-wrap"><table><thead><tr><th>Material</th><th>Calor</th><th>Manchas</th><th>Mantenimiento</th><th>Apariencia</th></tr></thead><tbody><tr data-best="quincho kitchen"><th>Granito</th><td>Muy resistente</td><td>Resistente</td><td>Bajo</td><td>Natural</td></tr><tr data-best="bath"><th>Mármol</th><td>Moderado</td><td>Más delicado</td><td>Medio / alto</td><td>Único</td></tr><tr data-best="kitchen bath"><th>Cuarzo</th><td>Moderado</td><td>Muy resistente</td><td>Bajo</td><td>Uniforme</td></tr></tbody></table></div><p class="note">La recomendación final depende del uso, color, terminación y disponibilidad de cada placa.</p></section>
<?php include 'includes/footer.php'; ?>
